### ISSUE TITLE
Please update runtime and platform.

### ISSUE THREAD

**Issue by queeup** [flathub/org.sugarlabs.Maze#4]
Please update to Gnome 42 runtime and new platform.

**Comment by tchx84** [comment]
Done, I am slowly updating all my org.sugarlabs.* apps.

**Comment by queeup** [comment]
@tchx84, I don't want to create new issue. Just I want to remind you `The GNOME 44 runtime is no longer supported as of March 20, 2024.` Thank you for your work.
